server:
  ## 服务运行端口
  port: 38010
spring:
  ## 服务名称
  application:
    name: shuyx-user
  ## 数据库配置
  datasource:
    url: jdbc:mysql://localhost:33306/shuyx_db?useSSL=true&serverTimezone=GMT%2B8 # serverTimezone=GMT%2B8 东八区时间
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  ## redis配置
  redis:
    database: 0
    host: localhost
    port: 36379
    password: 123456
  jackson:
    time-zone: GMT+8

# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis-plus开启sql日志
  mapper-locations: classpath:mapper/*.xml                # mybatis的手写 sql xml文件的位置。即resources目录中

# PageHelper分页插件配置，这个在使用mybatis进行分页时用到
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
