server:
  port: 38090
spring:
  application:
    name: shuyx-minio
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
minio:
  url: http://127.0.0.1:39000   #minio服务端地址。注意不要填为minio客户端地址
  accessKey: ymhTRVurqX2yqjJk8htn  # 凭证
  secretKey: 8IJbGdsfsStxNIKmLiOMraqThS8Yp6NyoZdoH2wk # 凭证密码
