server:
  # 服务运行端口
  port: 38080
spring:
  # 服务名称
  application:
    name: shuyx-gateway  # 服务名称
  cloud:
    ## gateway配置
    gateway:
      ## 跨域配置
      globalcors:
        cors-configurations:
          [ "/**" ]: ## 允许跨域访问的资源
            allowedOrigins: "*"   ## 允许跨域的来源
            allowedHeaders: "*"   ## 允许跨域的请求头
            allowedMethods: "*"   ## 允许跨域的请求方式。如GET,POST
      ## 路由配置
      routes:
        - id: shuyx-user
          uri: lb://shuyx-user
          predicates:
            - Path=/shuyx-user/**
        - id: shuyx-media
          uri: lb://shuyx-media
          predicates:
            - Path=/shuyx-media/**
        - id: shuyx-minio
          uri: lb://shuyx-minio
          predicates:
              - Path=/shuyx-minio/**
